package com.opengamma.strata.pricer.impl.tree;

import java.io.Serializable;
import java.util.List;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Set;

import org.joda.beans.Bean;
import org.joda.beans.BeanBuilder;
import org.joda.beans.BeanDefinition;
import org.joda.beans.ImmutableBean;
import org.joda.beans.JodaBeanUtils;
import org.joda.beans.MetaProperty;
import org.joda.beans.Property;
import org.joda.beans.PropertyDefinition;
import org.joda.beans.impl.direct.DirectFieldsBeanBuilder;
import org.joda.beans.impl.direct.DirectMetaBean;
import org.joda.beans.impl.direct.DirectMetaProperty;
import org.joda.beans.impl.direct.DirectMetaPropertyMap;

import com.google.common.collect.ImmutableList;
import com.opengamma.strata.collect.array.DoubleArray;
import com.opengamma.strata.collect.array.DoubleMatrix;

@BeanDefinition(builderScope = "private")
public final class RecombiningTrinomialTreeData implements ImmutableBean, Serializable {

  @PropertyDefinition
  private final DoubleMatrix stateValue;

  @PropertyDefinition
  private final ImmutableList<DoubleMatrix> transitionProbability;

  @PropertyDefinition
  private final DoubleArray discountFactor;

  public static RecombiningTrinomialTreeData of(
      DoubleMatrix stateValue,
      List<DoubleMatrix> transitionProbability,
      DoubleArray discountFactor) {
    // TODO check size of list, matrix
    return new RecombiningTrinomialTreeData(stateValue, transitionProbability, discountFactor);
  }

  public int getNumberOfSteps() {
    return transitionProbability.size();
  }

  public DoubleArray getStateValueAtLayer(int i) {
    return stateValue.column(i);
  }

  public DoubleMatrix getProbabilityAtLayer(int i) {
    return transitionProbability.get(i);
  }

  public double getDiscountFactorAtLayer(int i) {
    return discountFactor.get(i);
  }

  public double getSpot() {
    return stateValue.get(0, 0);
  }

  //------------------------- AUTOGENERATED START -------------------------
  ///CLOVER:OFF
  /**
   * The meta-bean for {@code RecombiningTrinomialTreeData}.
   * @return the meta-bean, not null
   */
  public static RecombiningTrinomialTreeData.Meta meta() {
    return RecombiningTrinomialTreeData.Meta.INSTANCE;
  }

  static {
    JodaBeanUtils.registerMetaBean(RecombiningTrinomialTreeData.Meta.INSTANCE);
  }

  /**
   * The serialization version id.
   */
  private static final long serialVersionUID = 1L;

  private RecombiningTrinomialTreeData(
      DoubleMatrix stateValue,
      List<DoubleMatrix> transitionProbability,
      DoubleArray discountFactor) {
    this.stateValue = stateValue;
    this.transitionProbability = (transitionProbability != null ? ImmutableList.copyOf(transitionProbability) : null);
    this.discountFactor = discountFactor;
  }

  @Override
  public RecombiningTrinomialTreeData.Meta metaBean() {
    return RecombiningTrinomialTreeData.Meta.INSTANCE;
  }

  @Override
  public <R> Property<R> property(String propertyName) {
    return metaBean().<R>metaProperty(propertyName).createProperty(this);
  }

  @Override
  public Set<String> propertyNames() {
    return metaBean().metaPropertyMap().keySet();
  }

  //-----------------------------------------------------------------------
  /**
   * Gets the stateValue.
   * @return the value of the property
   */
  public DoubleMatrix getStateValue() {
    return stateValue;
  }

  //-----------------------------------------------------------------------
  /**
   * Gets the transitionProbability.
   * @return the value of the property
   */
  public ImmutableList<DoubleMatrix> getTransitionProbability() {
    return transitionProbability;
  }

  //-----------------------------------------------------------------------
  /**
   * Gets the discountFactor.
   * @return the value of the property
   */
  public DoubleArray getDiscountFactor() {
    return discountFactor;
  }

  //-----------------------------------------------------------------------
  @Override
  public boolean equals(Object obj) {
    if (obj == this) {
      return true;
    }
    if (obj != null && obj.getClass() == this.getClass()) {
      RecombiningTrinomialTreeData other = (RecombiningTrinomialTreeData) obj;
      return JodaBeanUtils.equal(stateValue, other.stateValue) &&
          JodaBeanUtils.equal(transitionProbability, other.transitionProbability) &&
          JodaBeanUtils.equal(discountFactor, other.discountFactor);
    }
    return false;
  }

  @Override
  public int hashCode() {
    int hash = getClass().hashCode();
    hash = hash * 31 + JodaBeanUtils.hashCode(stateValue);
    hash = hash * 31 + JodaBeanUtils.hashCode(transitionProbability);
    hash = hash * 31 + JodaBeanUtils.hashCode(discountFactor);
    return hash;
  }

  @Override
  public String toString() {
    StringBuilder buf = new StringBuilder(128);
    buf.append("RecombiningTrinomialTreeData{");
    buf.append("stateValue").append('=').append(stateValue).append(',').append(' ');
    buf.append("transitionProbability").append('=').append(transitionProbability).append(',').append(' ');
    buf.append("discountFactor").append('=').append(JodaBeanUtils.toString(discountFactor));
    buf.append('}');
    return buf.toString();
  }

  //-----------------------------------------------------------------------
  /**
   * The meta-bean for {@code RecombiningTrinomialTreeData}.
   */
  public static final class Meta extends DirectMetaBean {
    /**
     * The singleton instance of the meta-bean.
     */
    static final Meta INSTANCE = new Meta();

    /**
     * The meta-property for the {@code stateValue} property.
     */
    private final MetaProperty<DoubleMatrix> stateValue = DirectMetaProperty.ofImmutable(
        this, "stateValue", RecombiningTrinomialTreeData.class, DoubleMatrix.class);
    /**
     * The meta-property for the {@code transitionProbability} property.
     */
    @SuppressWarnings({"unchecked", "rawtypes" })
    private final MetaProperty<ImmutableList<DoubleMatrix>> transitionProbability = DirectMetaProperty.ofImmutable(
        this, "transitionProbability", RecombiningTrinomialTreeData.class, (Class) ImmutableList.class);
    /**
     * The meta-property for the {@code discountFactor} property.
     */
    private final MetaProperty<DoubleArray> discountFactor = DirectMetaProperty.ofImmutable(
        this, "discountFactor", RecombiningTrinomialTreeData.class, DoubleArray.class);
    /**
     * The meta-properties.
     */
    private final Map<String, MetaProperty<?>> metaPropertyMap$ = new DirectMetaPropertyMap(
        this, null,
        "stateValue",
        "transitionProbability",
        "discountFactor");

    /**
     * Restricted constructor.
     */
    private Meta() {
    }

    @Override
    protected MetaProperty<?> metaPropertyGet(String propertyName) {
      switch (propertyName.hashCode()) {
        case -236449952:  // stateValue
          return stateValue;
        case 734501792:  // transitionProbability
          return transitionProbability;
        case -557144592:  // discountFactor
          return discountFactor;
      }
      return super.metaPropertyGet(propertyName);
    }

    @Override
    public BeanBuilder<? extends RecombiningTrinomialTreeData> builder() {
      return new RecombiningTrinomialTreeData.Builder();
    }

    @Override
    public Class<? extends RecombiningTrinomialTreeData> beanType() {
      return RecombiningTrinomialTreeData.class;
    }

    @Override
    public Map<String, MetaProperty<?>> metaPropertyMap() {
      return metaPropertyMap$;
    }

    //-----------------------------------------------------------------------
    /**
     * The meta-property for the {@code stateValue} property.
     * @return the meta-property, not null
     */
    public MetaProperty<DoubleMatrix> stateValue() {
      return stateValue;
    }

    /**
     * The meta-property for the {@code transitionProbability} property.
     * @return the meta-property, not null
     */
    public MetaProperty<ImmutableList<DoubleMatrix>> transitionProbability() {
      return transitionProbability;
    }

    /**
     * The meta-property for the {@code discountFactor} property.
     * @return the meta-property, not null
     */
    public MetaProperty<DoubleArray> discountFactor() {
      return discountFactor;
    }

    //-----------------------------------------------------------------------
    @Override
    protected Object propertyGet(Bean bean, String propertyName, boolean quiet) {
      switch (propertyName.hashCode()) {
        case -236449952:  // stateValue
          return ((RecombiningTrinomialTreeData) bean).getStateValue();
        case 734501792:  // transitionProbability
          return ((RecombiningTrinomialTreeData) bean).getTransitionProbability();
        case -557144592:  // discountFactor
          return ((RecombiningTrinomialTreeData) bean).getDiscountFactor();
      }
      return super.propertyGet(bean, propertyName, quiet);
    }

    @Override
    protected void propertySet(Bean bean, String propertyName, Object newValue, boolean quiet) {
      metaProperty(propertyName);
      if (quiet) {
        return;
      }
      throw new UnsupportedOperationException("Property cannot be written: " + propertyName);
    }

  }

  //-----------------------------------------------------------------------
  /**
   * The bean-builder for {@code RecombiningTrinomialTreeData}.
   */
  private static final class Builder extends DirectFieldsBeanBuilder<RecombiningTrinomialTreeData> {

    private DoubleMatrix stateValue;
    private List<DoubleMatrix> transitionProbability;
    private DoubleArray discountFactor;

    /**
     * Restricted constructor.
     */
    private Builder() {
    }

    //-----------------------------------------------------------------------
    @Override
    public Object get(String propertyName) {
      switch (propertyName.hashCode()) {
        case -236449952:  // stateValue
          return stateValue;
        case 734501792:  // transitionProbability
          return transitionProbability;
        case -557144592:  // discountFactor
          return discountFactor;
        default:
          throw new NoSuchElementException("Unknown property: " + propertyName);
      }
    }

    @SuppressWarnings("unchecked")
    @Override
    public Builder set(String propertyName, Object newValue) {
      switch (propertyName.hashCode()) {
        case -236449952:  // stateValue
          this.stateValue = (DoubleMatrix) newValue;
          break;
        case 734501792:  // transitionProbability
          this.transitionProbability = (List<DoubleMatrix>) newValue;
          break;
        case -557144592:  // discountFactor
          this.discountFactor = (DoubleArray) newValue;
          break;
        default:
          throw new NoSuchElementException("Unknown property: " + propertyName);
      }
      return this;
    }

    @Override
    public Builder set(MetaProperty<?> property, Object value) {
      super.set(property, value);
      return this;
    }

    @Override
    public Builder setString(String propertyName, String value) {
      setString(meta().metaProperty(propertyName), value);
      return this;
    }

    @Override
    public Builder setString(MetaProperty<?> property, String value) {
      super.setString(property, value);
      return this;
    }

    @Override
    public Builder setAll(Map<String, ? extends Object> propertyValueMap) {
      super.setAll(propertyValueMap);
      return this;
    }

    @Override
    public RecombiningTrinomialTreeData build() {
      return new RecombiningTrinomialTreeData(
          stateValue,
          transitionProbability,
          discountFactor);
    }

    //-----------------------------------------------------------------------
    @Override
    public String toString() {
      StringBuilder buf = new StringBuilder(128);
      buf.append("RecombiningTrinomialTreeData.Builder{");
      buf.append("stateValue").append('=').append(JodaBeanUtils.toString(stateValue)).append(',').append(' ');
      buf.append("transitionProbability").append('=').append(JodaBeanUtils.toString(transitionProbability)).append(',').append(' ');
      buf.append("discountFactor").append('=').append(JodaBeanUtils.toString(discountFactor));
      buf.append('}');
      return buf.toString();
    }

  }

  ///CLOVER:ON
  //-------------------------- AUTOGENERATED END --------------------------
}
